#!/bin/bash
#
#$-V
#
#$-cwd
#
#$-N InformationSet 
#
#$-j y
#
#$-o $JOB_NAME.o$JOB_ID
#
#$-e $JOB_NAME.e$JOB_ID
#
#$-pe 16way 4 
# number of total cores above
#
#$-q normal
#
#$-M gupta59@illinois.edu
#
#$-m be
#
#$-l h_rt=00:05:00
#
#$ -A TG-ASC050039N


~/gennodelist ~/.nodelist.$JOB_ID
#make test is retarded about nodelist
# change below
P="4"
K="8 "
for i in $P
do
for k in $K
do
./charmrun ++scalable-start ./hc 5 10 $k  \
   +p$i  ++nodelist  ~/.nodelist.${JOB_ID}  \
   +setcpuaffinity
done
done
